services:
  # Kratos migration
  kratos-migrate:
    image: oryd/kratos:latest
    depends_on:
      - postgres
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=warn
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  # Kratos main
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_DB=kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

  adminer:
    image: adminer:latest
    restart: always
    networks:
      - intranet
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: galkaev

networks:
  intranet:

volumes:
  kratos-sqlite:
